apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  protocol: nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azure-files-nfs-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: azurefile-csi-nfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: azure-files-nfs-svc
spec:
  selector:
    app: azure-files-nfs-pod
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-2
  labels:
    app: azure-files-nfs-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-files-nfs-pod 
  template:
    metadata:
      labels:
        app: azure-files-nfs-pod
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - azure-files-nfs-pod 
              topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: init-container
        image: busybox
        command: ['sh', '-c', "echo $(date +%Y-%m-%d:%H:%M:%S) - $(hostname) - ***POD STARTING*** >> /mnt/index.html"]
        volumeMounts:
        - mountPath: /mnt
          name: azure-files-nfs-volume
      containers:
      - name: busybox-writer
        image: busybox
        command:
        - sh
        - -c
        - "while true; do sleep 1; echo $(date +%Y-%m-%d:%H:%M:%S) - $(hostname) >> /mnt/index.html; done"
        volumeMounts:
        - mountPath: /mnt
          name: azure-files-nfs-volume
      - name: busybox-web
        image: busybox
        command:
        - sh
        - -c
        - "httpd -p 80 -f -v -h /mnt"
        volumeMounts:
        - mountPath: /mnt
          name: azure-files-nfs-volume
      volumes:
      - name: azure-files-nfs-volume
        persistentVolumeClaim:
          claimName: azure-files-nfs-pvc
